language: ruby
cache: bundler
gemfile:
- Gemfile
- chef-12.Gemfile
rvm:
- 2.4.2
- 2.3.5
script:
- bundle exec rubocop --lint --display-style-guide --extra-details --display-cop-names
- bundle exec rspec
